# Generated by Django 5.0.3 on 2024-06-06 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='')),
                ('product_name', models.CharField(default='default', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='newproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('ProductName', models.CharField(default='productname', max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default='productname', max_digits=10)),
                ('Brand', models.CharField(default='productname', max_length=100)),
                ('Description', models.CharField(default='productname', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='menformals',
            fields=[
                ('newproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.newproducts')),
            ],
            bases=('myapp.newproducts',),
        ),
        migrations.CreateModel(
            name='womenformals',
            fields=[
                ('newproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.newproducts')),
            ],
            bases=('myapp.newproducts',),
        ),
        migrations.CreateModel(
            name='Signuptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('place', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signuptable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
