# Generated by Django 5.0.3 on 2024-06-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menformals',
            new_name='accessories',
        ),
        migrations.RenameModel(
            old_name='womenformals',
            new_name='laptop',
        ),
    ]
