# Generated by Django 5.0.3 on 2024-06-06 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_menformals_accessories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='default', max_length=100)),
                ('last_name', models.CharField(default='default', max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product_name', models.CharField(default='default', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
