# Generated by Django 5.0.3 on 2024-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtable',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
